databases:
    mediawiki:
        host: "analytics-store.eqiad.wmnet"
        port: 3306
        creds_file: /etc/mysql/conf.d/stats-research-client.cnf
        db: enwiki # just a default, queries already specify it

defaults:
    db: mediawiki

reports:
    crosswiki_beta:
        granularity: days
        starts: 2016-02-18
        explode_by:
            wiki_db: crosswiki_dbs.txt
    rcfilters_beta:
        granularity: days
        starts: 2017-03-15
        explode_by:
            wiki_db: rcfilters_dbs.txt
