databases:
    mediawiki:
        auto_find_db_shard: true
        use_x1: true
        wiki_db_placeholder: wiki_db
        creds_file: /etc/mysql/conf.d/stats-research-client.cnf

defaults:
    db: mediawiki

reports:
    crosswiki_beta:
        granularity: days
        starts: 2016-02-18
        explode_by:
            wiki_db: crosswiki_dbs.txt
    rcfilters_beta:
        granularity: days
        starts: 2017-03-15
        explode_by:
            wiki_db: rcfilters_dbs.txt
