databases:
    x1:
        host: "x1-analytics-slave.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: enwiki # just a default, queries already specify it
    mediawiki:
        host: "analytics-store.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: enwiki # just a default, queries already specify it

defaults:
    db: x1

reports:

    monthly_production_and_consumption_of_notifications:
        granularity: months
        lag: 2678400 # 31 days in seconds
        starts: 2013-09-01
        explode_by:
            wiki_db: wiki_dbs.txt

    days_to_read:
        granularity: months
        lag: 2678400 # 31 days in seconds
        starts: 2015-09-01
        explode_by:
            wiki_db: wiki_dbs.txt
