databases:
    mediawiki:
        auto_find_db_shard: true
        use_x1: true
        wiki_db_placeholder: wiki_db
        creds_file: /etc/mysql/conf.d/stats-research-client.cnf

defaults:
    db: mediawiki

reports:

    monthly_production_and_consumption_of_notifications:
        granularity: months
        lag: 2678400 # 31 days in seconds
        starts: 2013-09-01
        explode_by:
            wiki_db: wiki_dbs.txt

    days_to_read:
        granularity: months
        lag: 2678400 # 31 days in seconds
        starts: 2015-09-01
        explode_by:
            wiki_db: wiki_dbs.txt
